 const Jobdata =  [
    {
       "id": 1,
       "company": "Photosnap",
       "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDLL2FyAeYaShg5h1YrW3gEyDHDCUb5o2_lw&usqp=CAU",
       "new": true,
       "featured": true,
       "position": "Senior Frontend Developer",
       "role": "Frontend",
       "level": "Senior",
       "postedAt": "1d ago",
       "contract": "Full Time",
       "location": "USA Only",
       "languages": ["HTML", "CSS", "JavaScript"],
       "tools": []
     },
     {
       "id": 2,
       "company": "Manage",
       "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsTSUyiVzgcEoi8IaiX4NOY51f-uy7I3rWhw&usqp=CAU",
       "new": true,
       "featured": true,
       "position": "Fullstack Developer",
       "role": "Fullstack",
       "level": "Midweight",
       "postedAt": "1d ago",
       "contract": "Part Time",
       "location": "Remote",
       "languages": ["Python"],
       "tools": ["React"]
     },
     {
       "id": 3,
       "company": "Account",
       "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsTSUyiVzgcEoi8IaiX4NOY51f-uy7I3rWhw&usqp=CAU",
       "new": true,
       "featured": false,
       "position": "Junior Frontend Developer",
       "role": "Frontend",
       "level": "Junior",
       "postedAt": "2d ago",
       "contract": "Part Time",
       "location": "USA Only",
       "languages": ["JavaScript"],
       "tools": ["React", "Sass"]
     },
     {
       "id": 4,
       "company": "MyHome",
       "logo":  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzPgQ7UV8bYgfm3d5adAcTw1JMEdu11LLYA&usqp=CAU",
       "new": false,
       "featured": false,
       "position": "Junior Frontend Developer",
       "role": "Frontend",
       "level": "Junior",
       "postedAt": "5d ago",
       "contract": "Contract",
       "location": "USA Only",
       "languages": ["CSS", "JavaScript"],
       "tools": []
     },
     {
       "id": 5,
       "company": "Loop Studios",
       "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzPgQ7UV8bYgfm3d5adAcTw1JMEdu11LLYA&usqp=CAU",
       "new": false,
       "featured": false,
       "position": "Software Engineer",
       "role": "Fullstack",
       "level": "Midweight",
       "postedAt": "1w ago",
       "contract": "Full Time",
       "location": "Worldwide",
       "languages": ["JavaScript"],
       "tools": ["Ruby", "Sass"]
     },
     {
       "id": 6,
       "company": "FaceIt",
       "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzPgQ7UV8bYgfm3d5adAcTw1JMEdu11LLYA&usqp=CAU",
       "new": false,
       "featured": false,
       "position": "Junior Backend Developer",
       "role": "Backend",
       "level": "Junior",
       "postedAt": "2w ago",
       "contract": "Full Time",
       "location": "UK Only",
       "languages": ["Ruby"],
       "tools": ["RoR"]
     },
     {
       "id": 7,
       "company": "Shortly",
       "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzPgQ7UV8bYgfm3d5adAcTw1JMEdu11LLYA&usqp=CAU",
       "new": false,
       "featured": false,
       "position": "Junior Developer",
       "role": "Frontend",
       "level": "Junior",
       "postedAt": "2w ago",
       "contract": "Full Time",
       "location": "Worldwide",
       "languages": ["HTML", "JavaScript"],
       "tools": ["Sass"]
     },
     {
       "id": 8,
       "company": "Insure",
       "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzPgQ7UV8bYgfm3d5adAcTw1JMEdu11LLYA&usqp=CAU",
       "new": false,
       "featured": false,
       "position": "Junior Frontend Developer",
       "role": "Frontend",
       "level": "Junior",
       "postedAt": "2w ago",
       "contract": "Full Time",
       "location": "USA Only",
       "languages": ["JavaScript"],
       "tools": ["Vue", "Sass"]
     },
     {
       "id": 9,
       "company": "Eyecam Co.",
       "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzPgQ7UV8bYgfm3d5adAcTw1JMEdu11LLYA&usqp=CAU",
       "new": false,
       "featured": false,
       "position": "Full Stack Engineer",
       "role": "Fullstack",
       "level": "Midweight",
       "postedAt": "3w ago",
       "contract": "Full Time",
       "location": "Worldwide",
       "languages": ["JavaScript", "Python"],
       "tools": ["Django"]
     },
     {
       "id": 10,
       "company": "The Air Filter Company",
       "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzPgQ7UV8bYgfm3d5adAcTw1JMEdu11LLYA&usqp=CAU",
       "new": false,
       "featured": false,
       "position": "Front-end Dev",
       "role": "Frontend",
       "level": "Junior",
       "postedAt": "1mo ago",
       "contract": "Part Time",
       "location": "Worldwide",
       "languages": ["JavaScript"],
       "tools": ["React", "Sass"]
     }
   ]

   export default Jobdata ; 